<?php

namespace JobsBundle\Repository;

/**
 * OffreTravailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OffreTravailRepository extends \Doctrine\ORM\EntityRepository
{
}
